### ISSUE TITLE
Set the social image

### ISSUE THREAD

**Issue by anki-code** [xonsh/xontrib-jupyter#11]
Hi @jnoortheen !
1. Please set the social image for the repo (below)
2. Please make the new release

Thanks!

![image](https://user-images.githubusercontent.com/1708680/225768468-b37a2c0f-4131-4ee0-948c-d907684b4e29.png)

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by jnoortheen** [comment]
done!
