### ISSUE TITLE
Rename pypi package from xontrib-jupyter-shell to xontrib-jupyter

### ISSUE THREAD

**Issue by anki-code** [xonsh/xontrib-jupyter#20]
Hi @jnoortheen! Could you please rename pypi package from `xontrib-jupyter-shell` to `xontrib-jupyter` to make the name consistent.

* repo `https://github.com/xonsh/xontrib-jupyter`
* install `xpip install xontrib-jupyter`  - instead of `xontrib-jupyter-shell`
* load `xontrib load jupyter`

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by jnoortheen** [comment]
@anki-code done! please update the readme and awesome-xontribs page
